[package]
name = "ranvier-synapse"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
version.workspace = true
edition.workspace = true
description = "Synapse data contracts for Ranvier automation flows"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
ranvier-core = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
