[package]
name = "ranvier-status"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
version = "0.1.1"
edition.workspace = true
description = "Static Status Page generator for Ranvier"

[dependencies]
ranvier-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tempfile = "3.10"
