[package]
name = "ranvier-runtime"
version = "0.1.0"
edition = "2021"
description = "Ranvier Runtime Layer - Async Execution and Bus"

[dependencies]
ranvier-flow = { path = "../flow", version = "0.1.0" }
async-trait = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
