[package]
name = "ranvier-http"
version = "0.1.0"
edition = "2021"

[dependencies]
ranvier-core = { workspace = true }
hyper = { workspace = true }
tower = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
tokio = { workspace = true }
bytes = { workspace = true }
serde_json = { workspace = true }
