[package]
name = "std-lib-demo"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ranvier-core = { workspace = true }
ranvier-std = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = "0.3"
anyhow = { workspace = true }
