[package]
name = "studio-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
ranvier-core = { path = "../../core" }
ranvier-runtime = { path = "../../runtime" }
ranvier-inspector = { workspace = true }
ranvier-macros = { path = "../../macros" }
async-trait = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json = { workspace = true }
chrono = { workspace = true }
