[package]
name = "ranvier"
version = "0.1.0"
edition = "2024"

[dependencies]
ranvier-core = { workspace = true }
ranvier-http = { workspace = true }
ranvier-macros = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
